##Notes:
##1. An AC cycle is required after completing the CPLD firmware update.
##2. To avoid AC cycle time overhead after each CPLD update, add all CPLD firmware details
##   in config and explicitly mention ac_cycle under "power_state" section to update all CPLD's
##   and Ac cycle at the end.
##3. To override/perform any power opertains at the end of firmware update, kindly mention it
##   under "power_state" section.
##4. To perform single or multi firmware update, update "Firmware_XD690" section as per the order.


## The value should be the path to the corresponding .fwpkg file. 
[Firmware_XD690]
1 = <BMC file path>
2 = <BIOS file path>
3 = <CPLD1 file path>
4 = <CPLD2 file path>
5 = <CPLD3 file path>
6 = <CPLD4 file path>
7 = <GPU file path>

## Restore the BMC configuration after a successful firmware update.
## Allowed values: yes or no (default: no)
[BMC_Settings]
restore_bmc_to_default = no

## also can be used by power_control.yml. Allowed options:
## "NA"           - just report the current power state, no action
## "on"           - power on if currently off
## "off"          - power off if currently on
## "reboot"       - Redfish graceful reboot
## "ac_cycle"     - IPMI AC power cycle
[Options]
power_state = NA


